### ISSUE TITLE
Doesn't seem to work with SD 3.5 Large

### ISSUE THREAD

**Issue by jetjodh** [chengzeyi/Comfy-WaveSpeed#10]
I get errors like this when running simple prompt with SD 3.5 Large and medium:
```!!! Exception during processing !!! 'OpenAISignatureMMDITWrapper' object has no attribute 'double_blocks'
[worker-comfy-container] Traceback (most recent call last):
[worker-comfy-container]   File "/comfyui/execution.py", line 328, in execute
[worker-comfy-container]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
[worker-comfy-container]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[worker-comfy-container]   File "/comfyui/execution.py", line 203, in get_output_data
[worker-comfy-container]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
[worker-comfy-container]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[worker-comfy-container]   File "/comfyui/execution.py", line 174, in _map_node_over_list
[worker-comfy-container]     process_inputs(input_dict, i)
[worker-comfy-container]   File "/comfyui/execution.py", line 163, in process_inputs
[worker-comfy-container]     results.append(getattr(obj, func)(**inputs))
[worker-comfy-container]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[worker-comfy-container]   File "/comfyui/custom_nodes/Comfy-WaveSpeed/fbcache_nodes.py", line 53, in patch
[worker-comfy-container]     diffusion_model.double_blocks,
[worker-comfy-container]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[worker-comfy-container]   File "/comfy/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
[worker-comfy-container]     raise AttributeError(
[worker-comfy-container] AttributeError: 'OpenAISignatureMMDITWrapper' object has no attribute 'double_blocks'
[worker-comfy-container] ```

**Comment by chengzeyi** [comment]
@jetjodh SD3 large is not supported yet. Please wait.
